### ISSUE TITLE
Come up with move names and their attack amount

### ISSUE THREAD

**Issue by noahd15** [utk-cs340-fall22/BattleBeasts#11]

**Comment by stephhill77** [comment]
range or close combat, status effects

**Comment by ColinC5** [comment]
Average beast max hp will be about 100. Right now I'm thinking we can have some attacks apply damage multiple times. As an example, if an attack does 12 total damage it could deal 6 damage twice or 4 damage 3 times. This becomes significant if we add armor values that simply subtract a flat amount from all damage taken. That means some attacks are affected by armor differently than others which creates opportunities for strategy.
For now we just need ideas.

**Comment by ChrisCanaday** [comment]
Moved to Sprint 2

**Comment by stephhill77** [comment]
a95c062ddab79d43c4a4b8c935b73154c7279cac
