### ISSUE TITLE
Team building 

### ISSUE THREAD

**Issue by stephhill77** [utk-cs340-fall22/BattleBeasts#13]
Allows user to choose from various monsters to build a team of 5? 6?

**Comment by ColinC5** [comment]
Play button on main menu leads to another menu with dropdown boxes to select one beasts, one type, and four attacks. This information gets translated into an integer which will can be passed to the Fight scene's script.
Initially this can just have drop down boxes with whatever.

**Comment by ChrisCanaday** [comment]
Moved to Sprint 2
