### ISSUE TITLE
Make bracket

### ISSUE THREAD

**Issue by noahd15** [utk-cs340-fall22/BattleBeasts#15]
Make bracket based on user input (might take longer than 1 sprint). Show where user is in the bracket

**Comment by noahd15** [comment]
Make bracket based on user input (might take longer than 1 sprint). Show where user is in the bracket

**Comment by ColinC5** [comment]
Separate "Bracket" scene.
To draw bracket: use number of players in tournament to calculate how many lines are needed and where they need to be drawn. Godot has functions to draw lines. I posted links to information about this in Discord.
For initial crude version: Display player's location in the bracket. Allow player to input if they win or lose. On a win advance the player through the bracket. On a loss return to the main menu. On winning the tournament return to the main menu.
Soon: Can enter fight scene from bracket scene, return to bracket when fight is over.

**Comment by noahd15** [comment]
32d3b497b912eddf82ded6a8af3dc645d6ba51f3

**Comment by noahd15** [comment]
Got everything needed for this sprint completed.
