### ISSUE TITLE
Monster Development

### ISSUE THREAD

**Issue by stephhill77** [utk-cs340-fall22/BattleBeasts#16]
Come up with names, types, skill set, basic flesh out of base stats

**Comment by ColinC5** [comment]
Determine how many types there will be and what they will be called. The player can choose a beast sprite, then the types they can choose from depend on what beast sprite they chose. The attacks they can choose from depends on what sprite and type they chose.
Average beast max hp will be about 100 and all incoming attacks will have their damage reduced by the beast's armor value. Base stats will include max hp, armor. Maybe more base stats but beast base stats aren't meant to be the main source of complexity. I think it would be more meaningful for the most complexity to come from things the player controls like the attacks they choose.

These stats will be stored in a text file, not a .cs file. I may end up writing a small program that creates this file in a consistent format.

**Comment by stephhill77** [comment]
Plan to have 10 total beast options. Currently have: 
Alzrius - Fire type (close combat)
Auril - Ice type (close combat)
Solanac - Poison type (distance)

Names and types will be further developed as the sprite development occurs. I'm thinking certain beasts will have strengths in distance attacks or close combat attacks.  

@noahd15: as these develop, attacks can be created based on these. 

Given that time allows I may add sprite sheets to create more animation to beasts for attacks.

**Comment by ChrisCanaday** [comment]
Moved to Sprint 2

**Comment by stephhill77** [comment]
d7a053f2cb2ffd764f3a6fdd27cf64752d54f18b

**Comment by stephhill77** [comment]
f4072b90467658140727d3fba417d74b6f909bef

**Comment by stephhill77** [comment]
b1c3e41e93e0423cc3d64c8816993ca8e343387c
