### ISSUE TITLE
Fight Outcome on Bracket

### ISSUE THREAD

**Issue by noahd15** [utk-cs340-fall22/BattleBeasts#27]
- indicates who won a match in globals.cs
- uses fight outcome from globals.cs to either advance player in the bracket or end the game. once this information is used/recorded the bracket resets the value in globals.cs to a neutral value

**Comment by ColinC5** [comment]
The fight scene now identifies the winner of a fight and exits the fight immediately while printing the result to the console. globals.cs just needs to be updated there as well.
