### ISSUE TITLE
Health bar

### ISSUE THREAD

**Issue by stephhill77** [utk-cs340-fall22/BattleBeasts#29]

**Comment by ColinC5** [comment]
Instantiated into the Fight scene similarly to the Fighters, meaning the health bars will be children of the top node in the Fight scene by calling AddChild().
Along with a simple health bar there should be some dynamic text that displays the beast's current health as a fraction of its maximum health value.
If you look at health bars in Pokemon games you will notice the health bar is displayed inside a box that also contains the Pokemon's name and level. Our health bar GUI element should contain the health bar itself as well as the health fraction, the player's name, and there should be space to display the beast's modifier (which will likely be a single word).
