### ISSUE TITLE
Fight scene messages

### ISSUE THREAD

**Issue by stephhill77** [utk-cs340-fall22/BattleBeasts#80]
Attack messages and win/loss messages pop on screen. So when the user doesn't have the debug window they can see what is happening. 
Examples:
"[Opponent] used [move name]"
"[Player] used "[move name]"
"[Opponent] is knocked out, [Player] wins"
"[Player] is knocked out, game over"

**Comment by ColinC5** [comment]
The text box displays information about each attack performed. Upon victory/loss the appropriate text should appear in the middle of the screen. The player should be able to click a button to advance to the bracket/main menu. We could also have the game automatically advance after a few seconds.
