### ISSUE TITLE
Fix Bracket hardcoding

### ISSUE THREAD

**Issue by noahd15** [utk-cs340-fall22/BattleBeasts#87]
- Pick beasts before fight starts (might have to modify them before fight starts because the opponents need to be visible the entire game)
- get rid of hardcoded stuff

**Comment by ColinC5** [comment]
Essential functions have been fixed. Almost all other bracket functions are still hardcoded but there is no time to fix this. Development will end soon anyway and the consequences of the hardcoding aren't completely obvious in-game.
